name: fluttersalonapp
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: any
  outline_material_icons: ^0.1.1
  google_fonts: any
  firebase_auth: any
  #firebase_auth_ui: any
  firebase_core: any
  flutter_riverpod: any
  nb_utils: ^4.4.12
  intl: ^0.17.0
  flutter_vector_icons: ^2.0.0
  cloud_firestore: ^4.1.0
  get:
  ntp: any
  add_2_calendar: any
 



    # Common
  share: ^2.0.4
  url_launcher: ^6.0.20
  http: ^0.13.4
  html: ^0.15.0
  package_info: ^2.0.2

  # IMAGES

  # STATE MANAGEMENT
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  # MAP
  google_maps_flutter: ^2.1.1

  # UI
  flutter_svg: ^1.1.6
  im_stepper: any
  flutter_calendar_carousel: ^2.4.1
  flutter_rating_bar: any
  flutter_datetime_picker: any

  
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - images/  
